apiVersion: v1
kind: Service
metadata:
  name: validating-webhook
  namespace: kube-addons
  labels:
    svc: validating-webhook
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: validating-webhook