apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mutating-webhook.mritd.me"
  namespace: oversold
webhooks:
  - name: "mutating-webhook.mritd.me"
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE","UPDATE"]
        resources:   ["nodes/status"]
        scope:       "*"
    clientConfig:
      service:
        name: "mutating-webhook"
        namespace: "oversold"
        path: /mutating/oversold
      caBundle: ${CA_BUNDLE}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Ignore