apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mutating-webhook
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - events
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - autoscaling
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups: [""]
    resources: ["nodes"]
    verbs:
      - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mutating-webhook
  namespace: oversold
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mutating-webhook
  namespace: oversold
subjects:
  - kind: ServiceAccount
    name: mutating-webhook
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mutating-webhook