apiVersion: v1
kind: Service
metadata:
  name: mutating-webhook
  namespace: kube-addons
  labels:
    svc: mutating-webhook
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: mutating-webhook